### ISSUE TITLE
Settings.initializeTerrainsItem fails unable to Create Terrain

### ISSUE THREAD

**Issue by Peter360** [caewok/fvtt-terrain-mapper#20]
Hi
PF2E : 5.12.1
Mapper :  0.1.0

When VTT first loads the following is being thrown.

pf2e.mjs:1617  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at ItemPF2e._preCreate (pf2e.mjs:1617:309499)
    at #preCreateDocumentArray (foundry.js:13541:31)
    at ClientDatabaseBackendPF2e._createDocuments (foundry.js:13428:73)
    at ClientDatabaseBackendPF2e.create (commons.js:8629:19)
    at async Proxy.createDocuments (commons.js:7958:23)
    at async Proxy.create (commons.js:8081:23)
    at async Settings.initializeTerrainsItem (settings.js:150:18)
    at async Object.fn (module.js:77:3)

**Comment by Peter360** [comment]
Thanks.

**Comment by caewok** [comment]
Added in Foundry v12, Terrain Mapper v0.3.0
