### ISSUE TITLE
Error while loading scene

### ISSUE THREAD

**Issue by TopSecretPorkChop** [caewok/fvtt-terrain-mapper#37]
I get the following error whenever I load a scene containing any region (even regions that have nothing to do with terrain). When I try to load **any** scene after I have tried loading the offending scene, I again get the same error. Disabling the module resolves the issue.

Error: Failed drawing interface canvas group: "refreshTerrainMapperMesh" is not defined as a supported RenderFlag option.. "refreshTerrainMapperMesh" is not defined as a supported RenderFlag option.
    at Hooks.onError (foundry.js:654:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at #draw (foundry.js:25053:15)
    at async Canvas.draw (foundry.js:24937:5)
    at async ScenePF2e.view (foundry.js:21358:7)Caused by: Error: "refreshTerrainMapperMesh" is not defined as a supported RenderFlag option.
    at #set (foundry.js:31605:23)
    at #set (foundry.js:31609:47)
    at #set (foundry.js:31609:47)
    at RenderFlags.set (foundry.js:31587:16)
    at foundry.js:26712:24

**Comment by ChasarooniZ** [comment]
![image](https://github.com/user-attachments/assets/04d8cba5-518c-498b-926d-ee8e083ee468)

**Comment by uniwars** [comment]
+1

**Comment by MaxswellSmart** [comment]
same. I rolled back to 3.3

**Comment by NdranC** [comment]
Same issue for me. Had to downgrade to 3.3

**Comment by sanhousdj** [comment]
+1

**Comment by caewok** [comment]
Should be fixed in v0.4.1.
