### ISSUE TITLE
Bug with variant encombered

### ISSUE THREAD

**Issue by CaosFR** [caewok/fvtt-terrain-mapper#54]
Hi ,

Thanks for your great module. If I use the variant encombered of dnd5e system I have a bug with your module : 

Foundry v12
Dnd 3.31
Terrain mapper 0.4.5
No other module enable

![image](https://github.com/user-attachments/assets/94655ddd-0df6-4301-8f17-c80080297357)

**Comment by CaosFR** [comment]
Same for all core effect

```
game:1 Uncaught (in promise) Error: undefined. The _id [dnd5epoisoned000] already exists within the parent collection: Actor [OJUmW18chuMQBzml] effects
[No packages detected]
    at /home/foundry/resources/app/dist/database/backend/server-backend.mjs:1:3158
    at Array.map (<anonymous>)
    at ServerDatabaseBackend._createDocuments (/home/foundry/resources/app/dist/database/backend/server-backend.mjs:1:3073)
    at ServerDatabaseBackend.create (/home/foundry/resources/app/common/abstract/backend.mjs:77:17)
    at async Semaphore._try (/home/foundry/resources/app/common/utils/semaphore.mjs:101:17)
```

**Comment by caewok** [comment]
What are you doing to get the error to show up? Can you walk me through the steps?

**Comment by CaosFR** [comment]
Thanks for your reply. I have made some tests. 

The problem stems from an incompatibility between module [automated-conditions-5e](https://github.com/thatlonelybugbear/automated-conditions-5e) and your work. Even if the latter is deactivated, traces remain and cause the above-mentioned errors.

Indeed, when an effect affects a person, an error is generated (not systematic). This is clearly visible when using the [Active-Auras](https://github.com/kandashi/Active-Auras), which regularly refreshes effects.

On a blank world, your module works fine, but if I activate then deactivate this module, I get errors when your module is running.

I don't think there's much you can do about it.

**Comment by CaosFR** [comment]
Thanks for your reply. I have made some tests.

It's very strange, The problem stems from an incompatibility between midi-qol (https://github.com/thatlonelybugbear/automated-conditions-5e) and your work. I hadn't checked because I think your modules are complementary (my bad).

If I disable your module or midi-qol. I have try with different configuration of midi (full , no automate), the problem persist.

**Comment by tweener67** [comment]
I have also seen a similar result which occurs anytime I use an active effect to add a condition it throws "The _id [dnd5ecursed00000] already exists within the parent collection". When the effect is later removed it throws "ActiveEffect "dnd5ecursed00000" does not exist!". I've tried adding a different condition and it throws dnd5e[condition] for each one.

In my case I have a spell which under effects applies a temporary condition. I have tried different conditions and it seems to work for all of them. Turning off Terrain-Mapper makes the error go away. I have not tried turning off MIDIQOL.

From the console window I get the following:

The _id [dnd5ecursed00000] already exists within the parent collection: Actor [RMuYEyBfrt6DrMy9] effects

Uncaught (in promise) Error: The _id [dnd5ecursed00000] already exists within the parent collection: Actor [RMuYEyBfrt6DrMy9] effects
[No packages detected]
    at /opt/foundryvtt/dist/database/backend/server-backend.mjs:1:3158
    at Array.map (<anonymous>)
    at ServerDatabaseBackend._createDocuments (/opt/foundryvtt/dist/database/backend/server-backend.mjs:1:3073)
    at ServerDatabaseBackend.create (/opt/foundryvtt/common/abstract/backend.mjs:77:17)
    at async Semaphore._try (/opt/foundryvtt/common/utils/semaphore.mjs:101:17)

When removing the  effect:

ActiveEffect "dnd5ecursed00000" does not exist!

foundry.js:3477 Uncaught (in promise) Error: ActiveEffect "dnd5ecursed00000" does not exist!
[No packages detected]
    at file:///opt/foundryvtt/dist/database/backend/server-backend.mjs:1:6671
    at Array.map (<anonymous>)
    at ServerDatabaseBackend._deleteDocuments (file:///opt/foundryvtt/dist/database/backend/server-backend.mjs:1:6641)
    at ServerDatabaseBackend.delete (file:///opt/foundryvtt/common/abstract/backend.mjs:174:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Semaphore._try (file:///opt/foundryvtt/common/utils/semaphore.mjs:101:17)

**Comment by CaosFR** [comment]
Hi, any news ?

**Comment by TimorSol** [comment]
I bumped into an similar issue in the A5e system. The same thing happens when I try to remove an effect as described in the post from @tweener67. 
When any token "falls" to 0 HP, the effects they get applied automatically (dead, defeated or unconscious or prone) are doubled or sometimes trippled. I have narrowed down the issue to strictly terrain mapper, no other modules are on. 

Replicate: take a token and make it take damage that takes it below 0HP. Example below, a double incapacitated character. 

![obraz](https://github.com/user-attachments/assets/4e04179b-8baa-4fd1-a817-d87c7edd6675)

**Comment by caewok** [comment]
Yes, I know the error exists, but will have to wait until v13 to try to address.

**Comment by caewok** [comment]
Try v14.0.1.
