### ISSUE TITLE
latest version breaks elevation ruler

### ISSUE THREAD

**Issue by ctbritt** [caewok/fvtt-terrain-mapper#62]
Hi, having some very strange behavior with the latest DAE and elevation ruler. 

As you can see, the elevation ruler behaves normally when you don't go in a region. But as soon as I drag into the region, which is using the default Underwater (Swimming) terrain, the ruler stops and I get that big error message. 

If I try to move the token around in the region, every square moved triggers that error and the ruler never shows up. 

Modules and other info: 
DAE 11.3.64
Elevation Ruler 0.10.11
libwrapper 1.13.0.0
socketlib 1.1.0
Region Active Effects 1.2.0
Terrain Mapper 0.4.6

Foundry Virtual Tabletop: Version 12 Stable, 12.331
Game System: dnd5e, 3.3.1
Client: Chromium/129.0.6668.59

Error message: 
https://cdn.discordapp.com/attachments/1287156848931241994/1287156870804672663/CleanShot_2024-09-21_at_16.50.44.png?ex=66f085c0&is=66ef3440&hm=05454628590cd89b8e2877155328c2e0a9f4eb172cea193d22874b9360c37a10&

when entering a region with default water terrain
https://cdn.discordapp.com/attachments/1287156848931241994/1287156871181897828/CleanShot_2024-09-21_at_16.52.01.png?ex=66f085c0&is=66ef3440&hm=267c3095cdb62566472e58550edc6b8bbed28d6a08f32fb197a4b64919fc12e7&

when moving around a region with default water terrain
https://cdn.discordapp.com/attachments/1287156848931241994/1287156871584546847/CleanShot_2024-09-21_at_16.52.16.png?ex=66f085c0&is=66ef3440&hm=774d1192c571d5bd0ea447887f0dcf5de3200ed315491f8e377b110596da8b9e&

Gif of what it looks like in action:
https://cdn.discordapp.com/attachments/1287156848931241994/1287215170191622255/CleanShot_2024-09-21_at_20.52.27.gif?ex=66f0bc0b&is=66ef6a8b&hm=6ce33b8c88b5bea53b30566c1ca4ac51e91f689a9714f9a41e480d7bfa9c34f1&

**Comment by a-mannered-bird** [comment]
Yup something went very wrong on my side also recently

**Comment by rapus95** [comment]
Can confirm. JS Exception:
```javascript
Uncaught (in promise) TypeError: Cannot redefine property: _inferredSource
[Detected 5 packages: system:dnd5e(4.0.4), vision-5e(2.5.3), elevationruler(0.10.14), lib-wrapper(1.13.2.0), touch-vtt(2.2.10)]
    at Function.defineProperty (<anonymous>)
    at UtilityActivity.prepareFinalData (base-activity.mjs:563:12)
    at FeatData.prepareFinalActivityData (activities.mjs:292:56)
    at FeatData.prepareFinalData (feat.mjs:114:10)
    at Item5e.prepareFinalAttributes (item.mjs:648:33)
    at actor.mjs:184:37
    at EmbeddedCollection.forEach (foundry-esm.js:5031:9)
    at Actor5e.prepareData (actor.mjs:184:16)
    at Actor5e.prepareData (actor.mjs:13:15)
    at MovePenalty.moveSpeedWithinRegions (MovePenalty.js:218:18)
    at MovePenalty.movementCostForGridSpace (MovePenalty.js:369:20)
    at MovePenalty.movementCostForSegment (MovePenalty.js:297:36)
    at Ruler.js:484:32
    at SquareGrid._measurePath (Grid.js:115:23)
    at 🎁foundry.grid.SquareGrid.prototype._measurePath#0 (libWrapper-wrapper.js:191:52)
    at SquareGrid.measurePath (foundry-esm.js:40093:12)
    at Ruler._computeDistance (foundry.js:36272:38)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511:22)
    at Ruler._computeDistance (Ruler.js:411:3)
    at 🎁CONFIG.Canvas.rulerClass.prototype._computeDistance#0 (libWrapper-wrapper.js:191:52)
    at Ruler.measure (foundry.js:36103:10)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511:22)
    at 🎁Ruler.prototype.measure#touch-vtt (touch-vtt.js:1:57255)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:639:16)
    at 🎁Ruler.prototype.measure#0 (libWrapper-wrapper.js:193:20)
    at Ruler._onMouseMove (foundry.js:36719:10)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511:22)
    at 🎁Ruler.prototype._onMouseMove#touch-vtt (touch-vtt.js:1:57176)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:639:16)
    at 🎁Ruler.prototype._onMouseMove#0 (libWrapper-wrapper.js:193:20)
    at #onDragLeftMove (foundry.js:25913:67)
    at MouseInteractionManager.callback (foundry.js:30834:17)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511:22)
    at 🎁MouseInteractionManager.prototype.callback#touch-vtt (touch-vtt.js:1:56232)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:639:16)
    at 🎁MouseInteractionManager.prototype.callback#0 (libWrapper-wrapper.js:193:20)
    at #handleDragMove (foundry.js:31213:26)
    at #handlePointerMove (foundry.js:31178:64)
    at vh.notifyListeners (EventBoundary.ts:1464:33)
    at vh.notifyTarget (EventBoundary.ts:658:14)
    at vh.propagate (EventBoundary.ts:310:18)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerMove (EventBoundary.ts:815:64)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerMove (EventSystem.ts:396:31)
```

**Comment by caewok** [comment]
Will revisit in v13.

**Comment by caewok** [comment]
Try v14.0.1.
